### ISSUE TITLE
Bungee?

### ISSUE THREAD

**Issue by leolifbom** [TJPlaysNow/Discord-Bot-API---JDA#2]
Is there any way to load the Bot with a Bungee plugin? Tried looking around and I can't find much.

**Comment by TJPlaysNow** [comment]
It should work with bungee, the only problem you'll have to make a custom thread class for bungee and a custom command interface for bungee too. Or you could just not use those functions within the bot api

--

Also if you do make these classes you could share them with the community by making a pole request!

**Comment by leolifbom** [comment]
Ended up doing it another way! Thanks though.
