### ISSUE TITLE
Event listeners?

### ISSUE THREAD

**Issue by BitesizedLion** [TJPlaysNow/Discord-Bot-API---JDA#5]
Are there any like type of event listeners for like incoming DMs?

**Comment by BitesizedLion** [comment]
Also, some proper docs would be nice since this is a very useful thing but it gets confusing sometimes.

**Comment by TJPlaysNow** [comment]
Yes there is a way to add event listeners, all you have to do is type:
```JAVA
bot.addEvent((e) -> {
    if (e instanceof MessageRecievedEvent) {
        MessageRecievedEvent event = (MessageRecievedEvent) e;
        //TODO: Stuff here.
        return true;
    }
    return false;
});
```
